Repository vessl-ai/hyperpocket, pull requests merged in 2025-02, with the labels that each got.

#67 fix: typo in`invoke` kwargs of `PocketOpenAI`
  libs/extensions/openai/hyperpocket_openai/pocket_openai.py
Labels: bug

#71 Fix: tool path typo in llamaindex tool calling example
  examples/llamaindex/tool-calling-agent/tool_calling_agent/agent.py
  examples/llamaindex/tool-calling-agent/uv.lock
Labels: bug

#34 Agent-119 OAuth 2.0 auth code gen
  libs/hyperpocket/hyperpocket/cli/__main__.py
  libs/hyperpocket/hyperpocket/cli/auth_oauth2.py
  libs/hyperpocket/hyperpocket/cli/auth_token.py
  libs/hyperpocket/hyperpocket/cli/codegen/auth/__init__.py
  libs/hyperpocket/hyperpocket/cli/codegen/auth/auth_oauth2_context_template.py
  libs/hyperpocket/hyperpocket/cli/codegen/auth/auth_oauth2_handler_template.py
  libs/hyperpocket/hyperpocket/cli/codegen/auth/auth_oauth2_schema_template.py
  libs/hyperpocket/hyperpocket/cli/codegen/auth/server_auth_template.py
Labels: enhancement

#37 Agent-112 Codegen for tool create and build
  libs/hyperpocket/README.md
  libs/hyperpocket/hyperpocket/cli/__main__.py
  libs/hyperpocket/hyperpocket/cli/codegen/tool/__init__.py
  libs/hyperpocket/hyperpocket/cli/codegen/tool/tool_main_template.py
  libs/hyperpocket/hyperpocket/cli/tool.py
  libs/hyperpocket/hyperpocket/tool/wasm/README.md
Labels: enhancement

#86 Add universal api token auth handler
  examples/hyperpocket/api_token_auth_example.py
  libs/hyperpocket/hyperpocket/auth/apitoken/README.md
  libs/hyperpocket/hyperpocket/auth/apitoken/__init__.py
  libs/hyperpocket/hyperpocket/auth/apitoken/context.py
  libs/hyperpocket/hyperpocket/auth/apitoken/token_context.py
  libs/hyperpocket/hyperpocket/auth/apitoken/token_handler.py
  libs/hyperpocket/hyperpocket/auth/apitoken/token_schema.py
  libs/hyperpocket/hyperpocket/auth/provider.py
  libs/hyperpocket/hyperpocket/server/auth/apitoken.py
  settings.toml
Labels: enhancement

#105 More detailed description for crewai
  docs/hyperpocket/supported-frameworks/crewai.md
Labels: documentation
